### ISSUE TITLE
No cargo version configured 

### ISSUE THREAD

**Issue by Ludea** [BlackDex/rust-musl#11]
Hi,

I get
```
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```
when using container with GHA:
```
jobs:
  build_container:
    runs-on: ubuntu-latest
    container: blackdex/rust-musl:aarch64-musl-stable-1.82.0
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
```

**Comment by BlackDex** [comment]
Strange, as you can see i kinda do the same during the test builds
https://github.com/BlackDex/rust-musl/actions/runs/11477497940/job/31939721088#step:14:9

Though that uses the docker run and not my image as GHA image.
I actually have never tried that, but in theory it should work. 

Maybe something in your checkout is overwriting something?
Ill have to test this my self to see what happens.

Is the repo/branch you use for this public?

**Comment by Ludea** [comment]
https://github.com/Ludea/lucle/actions/runs/11540151227/job/32120633661

**Comment by BlackDex** [comment]
Strange, when i try to use [act](https://github.com/nektos/act), it seems to work just fine.

``bash
act push -j build_container
```

I suspect it has something to do with some default env's Github sets. Ill check a bit further.

**Comment by BlackDex** [comment]
You can probably fix this for now by setting:

```yaml
env:
  HOME: /root
```

**Comment by Ludea** [comment]
```
env:
  HOME: /root
```
Fix my issue, thanks

**Comment by BlackDex** [comment]
Ok, cool I'm working on a fix for this so that the next build's will be supported this way.

**Comment by BlackDex** [comment]
@Ludea, you should now be able to remove that `env` again. I fixed the images.

**Comment by Ludea** [comment]
Now I get `/__w/_temp/b84a7ab6-8893-49f7-8d31-b598ae0128ba.sh: 1: cargo: not found
Error: Process completed with exit code 127 `

**Comment by Ludea** [comment]
I try with `ghcr.io/blackdex/rust-musl:aarch64-musl-nightly-2024-10-25`, and it works as expected (like your test)
With `ghcr.io/blackdex/rust-musl:aarch64-musl` still get issue

**Comment by BlackDex** [comment]
Yea i noticed. GitHub Actions is doing something strange.

**Comment by BlackDex** [comment]
I have it working now, and i tested it using a fork of your project.
The images are currently being built and once done it should be able to run without any extra env needed to be set.

Fixed via 8831be56e896d22aea117ec2cb8d6051a7fef46b
